### ISSUE TITLE
使用的是centos 系统 在最后一步的安装的时候直接报错了不知道怎么解决 求大佬解决一下

### ISSUE THREAD

**Issue by 806482873** [dspurl/dsshop#279]
chunk-vendors.1480be5a.js:15 Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'type')
    at Uc.<computed> [as error] (chunk-vendors.1480be5a.js:15:28173)
    at chunk-79a75d9a.d53c65a3.js:1:2098

![image](https://user-images.githubusercontent.com/50004321/228721046-58ff6fef-6c46-42a5-be92-b738a9e16d50.png)

https://user-images.githubusercontent.com/50004321/228721069-09596414-05db-4788-8a75-a698355c986a.jpg

**Comment by dspurl** [comment]
![image](https://user-images.githubusercontent.com/49799121/228721996-f8b5407e-2075-4837-b1a5-62d7a22702ad.png)
通过Network查看问题，一般后端会给报错原因

**Comment by 806482873** [comment]
是这个原因吗？
![image](https://user-images.githubusercontent.com/50004321/228722897-62eb2752-7239-4241-91ec-cb0cf846413c.png)

**Comment by 806482873** [comment]
你们有什么交流群吗我想进去看看其他人怎么弄的？

**Comment by dspurl** [comment]
![image](https://user-images.githubusercontent.com/49799121/228723729-c17c44a6-15c0-4580-8453-83da54bc80ec.png)

看dispose.php那块
如果有错，看dispose.php源码去调试

**Comment by dspurl** [comment]
没有群，没有精力去管理群，群里重复性的回答太频繁了，还不如这里的，帮一个人解决了，碰到相同问题的就都能解决

**Comment by 806482873** [comment]
![image](https://user-images.githubusercontent.com/50004321/228724054-2d5f842d-ac18-46ae-a80a-2c599ce6f3a0.png)
好吧 谢谢  我是java 工程师 最近才接触php 但是看起来好像没有报错

**Comment by 806482873** [comment]
![image](https://user-images.githubusercontent.com/50004321/228724356-793737ab-784e-4b73-a5dd-ca2e2b66bd2b.png)

**Comment by dspurl** [comment]
![image](https://user-images.githubusercontent.com/49799121/228725448-5a5aed23-a14f-48a8-8c55-56ca8a521ef7.png)

**Comment by 806482873** [comment]
![image](https://user-images.githubusercontent.com/50004321/228725683-502676ec-7057-4454-ac1f-97eedd0d469e.png)
<br />
<b>Warning</b>:  mysqli::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known in <b>/www/wwwroot/dsshop-3.2.2/api/public/install/api/dispose.php</b> on line <b>23</b><br />
<br />
<b>Warning</b>:  mysqli::__construct(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name or service not known in <b>/www/wwwroot/dsshop-3.2.2/api/public/install/api/dispose.php</b> on line <b>23</b><br />
{"code":0,"msgCode":"\u8fde\u63a5\u5931\u8d25\uff1aphp_network_getaddresses: getaddrinfo failed: Name or service not known","msg":""}

看到了

**Comment by 806482873** [comment]
我这边有 vue技术 而且这个项目我觉得很不错 想搭建起来看看

**Comment by 806482873** [comment]
方便教我处理一下吗？ 谢谢

**Comment by dspurl** [comment]
mysql的问题
解决思路：
1、百度php_network_getaddresses: getaddrinfo failed: Name or service not known in，根据解决方法去操作
2、打开dispose.php，23行，把mysql配置信息打印出来，看下是否能正常获取，不行的话，从第一步开始调试，看问题出在哪，去解决它

**Comment by dspurl** [comment]
mysql的问题
解决思路：
1、百度php_network_getaddresses: getaddrinfo failed: Name or service not known in，根据解决方法去操作
2、打开dispose.php，23行，把mysql配置信息打印出来，看下是否能正常获取，不行的话，从第一步开始调试，看问题出在哪，去解决它

**Comment by 806482873** [comment]
好的 我试试 谢谢

**Comment by 806482873** [comment]
![image](https://user-images.githubusercontent.com/50004321/228738100-23c33d77-5c71-4f60-ac02-c26d50347280.png)
打印上面的是有值得 但是打印$link 里面所有的参数都是 null  百度也没有准确的解决办法  不知道大佬能不能在指点一下？

**Comment by 806482873** [comment]
![image](https://user-images.githubusercontent.com/50004321/228740485-a29fb314-f9c0-4eef-ac0f-dcf330496fa1.png)
应该是这个ip的问题
